spring.application.name=springsecurity

spring.datasource.url=jdbc:mysql://localhost:3306/studentdb2
spring.datasource.username=root
spring.datasource.password=${workbench_pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt-secret=TnD3bOZIByNS5OrHdZ+8+qwzEFM0E2il0I0DZYb+urA=

app-jwt-expiration-milliseconds=604800000